name: Node JS Testing
on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  pull-requests: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup nodes
        uses: actions/setup-node@v4
        with:
          node-version: 20.0

      - name: Install dependencies
        run: npm install

      - name: Run Test API
        run: API_KEY=${{ secrets.API_KEY }} npm test
